In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('Development Index.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.head()

Population  Area (sq. mi.)  ...  Infant mortality   Development Index
0     9944201         1284000  ...              93.82                  2
1     5450661           43094  ...               4.56                  4
2    26783383          437072  ...              50.25                  2
3        9439             102  ...               7.35                  4
4     3431932          176220  ...              11.95                  3

[5 rows x 7 columns]

In [14]:
#pre
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy_score(y_test, y_pred)

[[ 4  0  0  0]
 [ 3  6  1  0]
 [ 0  3 22  2]
 [ 0  0  2 14]]


0.8070175438596491